cassandra:
  image: cassandra:2.1.5
  ports:
    - "9160:9160"
elasticsearch:
  image: elasticsearch:1.5.2
  ports:
    - "9200:9200"
titan:
  build: .
  ports:
    - "8182:8182"
    - "8183:8183"
    - "8184:8184"
  links:
    - cassandra
    - elasticsearch
